### ISSUE TITLE
loss problems

### ISSUE THREAD

**Issue by Kongbaikb** [MCG-NJU/SparseBEV#11]
I have trained more than 10 epochs, and the loss value is around 10. Is this normal?

**Comment by afterthat97** [comment]
Yes. Here is the loss curve for your reference:

![image](https://github.com/MCG-NJU/SparseBEV/assets/24912012/a6c3b823-0b3c-4b51-b668-de20660de51f)

**Comment by Kongbaikb** [comment]
Thank you.
