### ISSUE TITLE
config problems

### ISSUE THREAD

**Issue by Kongbaikb** [MCG-NJU/SparseBEV#16]
Which experimental configuration in the paper corresponds to the configuration file "r50_nuimg_704x256. py"?
<img width="876" alt="image" src="https://github.com/MCG-NJU/SparseBEV/assets/91193040/d23b2cf7-0e94-410e-a047-b028b31ca2e3">

**Comment by afterthat97** [comment]
Ablation.

**Comment by Kongbaikb** [comment]
What configuration files should be used for training the two experimental results on the above image?

**Comment by afterthat97** [comment]
r50_in1k_704x256
r50_nuimg_704x256_400q_36ep

**Comment by Kongbaikb** [comment]
Which experimental setting in the paper corresponds to "r50_nuimg_704x256. py"?
