### ISSUE TITLE
A mistake in the calculation of rotation matrix？

### ISSUE THREAD

**Issue by xinbangzhang123** [MCG-NJU/SparseBEV#21]
Hi, there may be a mistask in the calculation of rotation matrix, the "sensor2global_rotation_past“ should be "sensor2global_rotation_past.T" in the following line.
https://github.com/MCG-NJU/SparseBEV/blob/main/loaders/pipelines/loading.py#L17

**Comment by afterthat97** [comment]
Why? maybe you should check the definition of 'sensor2global_rotation' here: 

https://github.com/MCG-NJU/SparseBEV/blob/78bb2780b465659e6794b62f78dff802216b20a1/gen_sweep_info.py#L28

**Comment by xinbangzhang123** [comment]
Indeed, that is fine.
