### ISSUE TITLE
Change backbone

### ISSUE THREAD

**Issue by Orange-rightperson** [MCG-NJU/SparseBEV#22]
Hello, I use the swin as model's backbone, and I find that enen swin-t can not support to run . I use 4 A100 gpus and set batch size 4.

**Comment by afterthat97** [comment]
what do you mean by "support"?

**Comment by Orange-rightperson** [comment]
@afterthat97  the gpu's usage is out of memory,  I use 1 batch per gpu even out of memory

**Comment by Orange-rightperson** [comment]
@afterthat97 But the settings can run bevformer, this model should be smaller than bevformer theroretically

**Comment by afterthat97** [comment]
try using single frame, or reducing resolution to 704x256

**Comment by Orange-rightperson** [comment]
Ok
