### ISSUE TITLE
Result differences

### ISSUE THREAD

**Issue by linchaozhang** [MCG-NJU/SparseBEV#23]
Why is it that the NDS of the model I trained using the "r50_nuimg_704x256" configuration file is only 44.83, but map is 44.47

**Comment by linchaozhang** [comment]
Epoch [24/24][3500/3517] loss: 8.76 
mAP: 0.4448
mATE: 0.5992
mASE: 0.7019
mAOE: 1.5652
mAVE: 0.2543
mAAE: 0.1869
NDS: 0.4482

**Comment by afterthat97** [comment]
Your mmdet3d version is not v1.0.0

**Comment by explorer-shy** [comment]
Use mmdet3d version 0.17.1 to test the weight given by the author. The results are similar. However, since the definition of LidarInstanceBox is different and the data_converter.py is also different.

**Comment by rkdckddnjs9** [comment]
What version is correct?
i trained v1.0.0rc6, but result is similar this issue
