### ISSUE TITLE
scale weights shape

### ISSUE THREAD

**Issue by zhangjinsong3** [MCG-NJU/SparseBEV#24]
Thank you for your pretty work. But
Why the shape of scale_weights is diff with sample_points_cam.
scale_weights           [**BGT**, Q, P, 4]
sample_points_cam  [**BTG**, Q, P, 3]

```
    # reorganize the tensor to stack T and G to the batch dim for better parallelism
    sample_points_cam = sample_points_cam.reshape(B, T, Q, G, P, 1, 3)
    sample_points_cam = sample_points_cam.permute(0, 1, 3, 2, 4, 5, 6)  # [B, T, G, Q, P, 1, 3]
    sample_points_cam = sample_points_cam.reshape(B*T*G, Q, P, 3)
    
    # reorganize the tensor to stack T and G to the batch dim for better parallelism
    scale_weights = scale_weights.reshape(B, Q, G, T, P, -1)
    scale_weights = scale_weights.permute(0, 2, 3, 1, 4, 5)
    scale_weights = scale_weights.reshape(B*G*T, Q, P, -1)
```

**Comment by afterthat97** [comment]
The last dim of `scale_weights` means the number of the multi-level feature maps (typically c2, c3, c4 and c5, so there are 4 in total), it has no relationship with the last dim of `sample_points_cam`.

**Comment by zhangjinsong3** [comment]
Not the last dim but the first dim. first of scale_weights is **[BGT]** but sample_points_cam is **[BTG]**. I thank it will casue sampled-feature multiply a scale from another **Frame**

**Comment by afterthat97** [comment]
Awesome! You found a bug in SparseBEV...

**Comment by zhangjinsong3** [comment]
Thus, Is it means that the model do not learnt a useful scale_weights?

**Comment by afterthat97** [comment]
Perhaps. I have fixed the bug and retrained the model, but the performance is the same as before. It looks like these scale weights have the same distribution across different groups and frames. So I will just leave this unchanged. Thank you!
