### ISSUE TITLE
visualize

### ISSUE THREAD

**Issue by zhujun3753** [MCG-NJU/SparseBEV#25]
Could someone tell me how to visualize the results?

**Comment by afterthat97** [comment]
visualize the predicted bbox?

**Comment by zhujun3753** [comment]
Yeah

**Comment by afterthat97** [comment]
Okay, we will provide a visualization script soon.

**Comment by zhujun3753** [comment]
Thanks

**Comment by Debrove** [comment]
@afterthat97 Hi! Could you please also provide a visualization script for Figure 6 in the paper?

**Comment by afterthat97** [comment]
@Debrove Okay.

**Comment by afterthat97** [comment]
You should be able to visualize the predictions and sampling points now.

**Comment by zhujun3753** [comment]
Thanks a lot!!!!
