### ISSUE TITLE
Joint BEV Segmentation and 3D detection with SparseBEV

### ISSUE THREAD

**Issue by abhi1kumar** [MCG-NJU/SparseBEV#26]
Hi SparseBEV authors,
Thank you for your excellent work and for releasing all (including test) models. 

I wanted to do a joint detection and BEV segmentation on the SparseBEV framework similar to [BEVerse](https://arxiv.org/abs/2205.09743) and [BEVFormer](https://arxiv.org/abs/2203.17270). BEVerse and BEVFormer take the dense BEV features and attach heads such as BEV Segmentation heads to achieve this goal. SparseBEV is a query-based pipeline; therefore, the outputs are also query-based. 

Could you explain how I should extend SparseBEV for the BEV segmentation task? Please note that I do not need a working implementation from you. Suggestions/directions are fine. I can implement the stuff on my end :)

PS- My initial thought is to use the latent `query_features` from the `SparseBEVTransformerDecoderLayer` available at this [line](https://github.com/MCG-NJU/SparseBEV/blob/78bb2780b465659e6794b62f78dff802216b20a1/models/sparsebev_transformer.py#L172). However, the dimensions of   `query_feat` is `B x Q x C` and not something with BEV width and BEV height.

**Comment by afterthat97** [comment]
It's a good question and we are still working on it. Please stay tuned, many thanks!

**Comment by abhi1kumar** [comment]
Thank you @afterthat97 for your quick clarification. I will rephrase my question. 

I need dense BEV features of your sparseBEV pipeline for experimentation (`b x c x 200 x 200` sized tensors for samples). Is this type of feature available in the sparseBEV?

**Comment by afterthat97** [comment]
No. SparseBEV aims to avoid the construction of a dense 200x200 BEV feature.
