### ISSUE TITLE
Question for the usage of temporal information in the paper 

### ISSUE THREAD

**Issue by Debrove** [MCG-NJU/SparseBEV#28]
Hi! I am very interested in SparseBEV. Please point out my mistake, if I misunderstand the paper.

There are three components: SASA, Spatio-temporal Sampling and Adaptive Mixing. The first two components focus on spatial information and only Adaptive Mixing deals with temporal information.

Because in Spatio-temporal Sampling, the features maintain the dimension of Frames without interaction across frames.

Looking forward to your reply! Thank you!

**Comment by afterthat97** [comment]
You are right! 👍

**Comment by Debrove** [comment]
Thanks for your quick reply！👍
