### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Orange-rightperson** [MCG-NJU/SparseBEV#29]
Hello, I use your vov pretrained model ,and try to evaluate it with 4 A100, it reminds me that cuda out of memory, could please help me ?

**Comment by afterthat97** [comment]
Try using single GPU for evaluation

**Comment by Orange-rightperson** [comment]
@afterthat97 Thanks for your replying , what is the difference between single GPU and multi GPUS?

**Comment by Orange-rightperson** [comment]
@afterthat97  Thank you so much

**Comment by afterthat97** [comment]
You are welcome. Is your A100 40GB? We use A100-80G and it runs well regardless of online/offline testing.
