### ISSUE TITLE
关于预训练权重下载问题

### ISSUE THREAD

**Issue by BarryGustin** [MCG-NJU/SparseBEV#32]
您好，关于预训练权重，请问在哪里下载？

**Comment by afterthat97** [comment]
您再仔细看看readme呢

**Comment by afterthat97** [comment]
https://github.com/open-mmlab/mmdetection3d/tree/main/configs/nuimages

**Comment by WZWAsuna** [comment]
> https://github.com/open-mmlab/mmdetection3d/tree/main/configs/nuimages
> 
> @WZWAsuna

非常感谢！
