### ISSUE TITLE
V2-99 和Dual-Swin-T哪个主干网络好

### ISSUE THREAD

**Issue by rubbish001** [MCG-NJU/SparseBEV#34]
你用Dual-Swin-T跑过吗，效果是不是比v299要好，我看目前主流的都是Dual-Swin-T这个主干网络

**Comment by rubbish001** [comment]
在请教一个问题，我现在弄了一个融合的模型，在val集上有mAp0.696，但是提交nuscenes只有0.63的精度，差距很大，一般是什么原因导致的

**Comment by afterthat97** [comment]
融合模型请移步CMT
