### ISSUE TITLE
Does sparseBEV support training with a single frame?

### ISSUE THREAD

**Issue by Cc-Hy** [MCG-NJU/SparseBEV#35]
Hi, I'd like to ask if sparseBEV supports training without temporal inputs.

**Comment by afterthat97** [comment]
https://github.com/MCG-NJU/SparseBEV/blob/e9dca314b7995b783bf266fdb2357fbc721d4bc1/configs/r50_nuimg_704x256.py#L24-L29

Set num_frames = 1 and num_points = 32.
