### ISSUE TITLE
Pretrained Models Installation

### ISSUE THREAD

**Issue by CeoiZidung** [MCG-NJU/SparseBEV#36]
您好~gdrive的pretrained模型下载实在太慢了，您能把文件上传到其他国内盘上吗。

**Comment by afterthat97** [comment]
好吧，我想想办法

**Comment by MiraclesinWang** [comment]
您好，我们已将所有权重上传至其他网盘。
|Setting      |Url      |
| ---- | ---- |
| r50_nuimg_704x256                   | https://cloud.189.cn/web/share?code=byYjee7ja2Ub（访问码：7son） |
| r50_nuimg_704x256_400q_36ep         | https://cloud.189.cn/web/share?code=vu6NzuuIFvUj（访问码：cjz1） |
| r101_nuimg_1408x512                 | https://cloud.189.cn/web/share?code=eAr63ajeaaIb（访问码：6v8j） |
| vov99_dd3d_1600x640_trainval_future | https://cloud.189.cn/web/share?code=jmEZrejMvUjm（访问码：m6kk） |

**Comment by CeoiZidung** [comment]
太棒了！感谢你们这么认真负责维护这个repo~

**Comment by afterthat97** [comment]
哈哈，感谢你对我们工作的关注

**Comment by Puiching-Memory** [comment]
这实在是太棒了，你可以将这个issue重新打开或置顶吗？

**Comment by afterthat97** [comment]
好了
