### ISSUE TITLE
Can't find `sample_infos = pickle.load(open(os.path.join(args.data_root, 'nuscenes_infos_train.pkl'), 'rb'))`

### ISSUE THREAD

**Issue by matrix97317** [MCG-NJU/SparseBEV#37]
Hi, I can't find this file "nuscenes_infos_train.pkl", could you explain it.

**Comment by afterthat97** [comment]
It's generated by the official mmdetection3d, see https://mmdetection3d.readthedocs.io/en/latest/user_guides/dataset_prepare.html

**Comment by matrix97317** [comment]
Thanks
