### ISSUE TITLE
 img_curr_large = img[:, i]  # [B, 6, C, H, W] IndexError: index 1 is out of bounds for dimension 1 with size 1

### ISSUE THREAD

**Issue by matrix97317** [MCG-NJU/SparseBEV#40]
when world size==1， under test_mode, occur the following error:
` img_curr_large = img[:, i]  # [B, 6, C, H, W]
IndexError: index 1 is out of bounds for dimension 1 with size 1`

**Comment by afterthat97** [comment]
which config?

**Comment by matrix97317** [comment]
configs/r50_nuimg_704x256.py

**Comment by afterthat97** [comment]
more details? it works fine on my server.

**Comment by matrix97317** [comment]
![image](https://github.com/MCG-NJU/SparseBEV/assets/76250408/8372795c-8f39-48b0-9b56-4b27713b0564)
if  num_frames = len(img_filenames) // 6  change to  num_frames = N//6, it work.

**Comment by matrix97317** [comment]
@afterthat97 , when world size==1,  can I use  test offline model?
![screenshot-20231113-195804](https://github.com/MCG-NJU/SparseBEV/assets/76250408/be57808c-89a4-45cb-b253-e53bf1d03591)
![screenshot-20231113-195730](https://github.com/MCG-NJU/SparseBEV/assets/76250408/83535d68-f5cf-4a9e-b801-de636422ad2a)
