### ISSUE TITLE
Question about absolute velo

### ISSUE THREAD

**Issue by iMbaGong** [MCG-NJU/SparseBEV#42]
Thanks for open-source great work!
I have a question about absolute velo computation
https://github.com/MCG-NJU/SparseBEV/blob/4d028e960fba5b3aa4fe5bb1170d9b21505a8d39/models/sparsebev_transformer.py#L178-L183
Why I have to div the velo with time here? Thanks a lot!

**Comment by afterthat97** [comment]
velocity = distance / time

The model predicts distance, so we need to divide it by time.

**Comment by iMbaGong** [comment]
I just didn‘t see it already a new prediction, i thought it was same as used in sampling then. Thanks a lot!
