### ISSUE TITLE
Is there any reason for setting the maximum sampling point to 32?

### ISSUE THREAD

**Issue by Qidian213** [MCG-NJU/SparseBEV#45]
https://github.com/MCG-NJU/SparseBEV/blob/4d028e960fba5b3aa4fe5bb1170d9b21505a8d39/models/csrc/msmv_sampling/msmv_sampling.cpp#L3

Can I set more sampling points ?
Thanks !

**Comment by afterthat97** [comment]
It's an upper limit of the number of sampling points. Of course you can set it to 64, 128, or even more, but be aware that the memory cost increases with it.

**Comment by Qidian213** [comment]
Thanks
