### ISSUE TITLE
SparseOcc questions

### ISSUE THREAD

**Issue by vehxianfish** [MCG-NJU/SparseBEV#47]
Hi, @afterthat97. SparseOcc is a wonderful work and I expect to expand the method. Do you have a timetable to release the code?
Looking forward to your reply.
Best wishes!

**Comment by afterthat97** [comment]
We are still working on it, please stay tuned, thanks!

**Comment by zbaishancha** [comment]
> We are still working on it, please stay tuned, thanks!

Hello, have read this paper and it's really an awesome work, may I ask about how soon will the code be published?

**Comment by afterthat97** [comment]
within one month, I guess. Thanks for your interest:)

**Comment by Qidian213** [comment]
@afterthat97 请教下，现在开源计划如何呢，迫不及待的想要follow一下

**Comment by afterthat97** [comment]
我们过一两周就会挂一版新的出来了，同时还会开源代码
