### ISSUE TITLE
Question about merging SparseBEV into the MMDection3D Framework.

### ISSUE THREAD

**Issue by tualatinlz** [MCG-NJU/SparseBEV#49]
I am attempting to merge SparseBEV into the MMDection3D Framework and am training the model using the MMDection3D command:
`bash tools/dist_train.sh configs/sparsebev/r50_nuimg_704x256.py 8 `
However, I've encountered an issue where the r50_nuimg_704x256.py configuration consumes over 48GB of GPU memory. Additionally, after I shorten the timing fusion length. There's a significant variation in memory usage across the GPUs. After training for 24 epochs, the NDS  remains very low. I would like to inquire about the expected GPU memory usage for training with this configuration on eight GPUs and whether there might be an error in my approach to merging and training the model.

**Comment by afterthat97** [comment]
Thanks for your effort! Looks like there is a lot of detail here. You can reach me by email: afterthat97@gmail.com
