### ISSUE TITLE
if this model can be used for BEV segmentation

### ISSUE THREAD

**Issue by raozhongyu** [MCG-NJU/SparseBEV#5]
Thanks for your great job. I'd like to konw if this model can be used for BEV segmentation?

**Comment by afterthat97** [comment]
Theoretically, it is possible. You can do it like PETRv2.

**Comment by raozhongyu** [comment]
Thanks a lot.

**Comment by zbaishancha** [comment]
> Thanks a lot.

Hello, did you migrate successfully? Can you share the performance of your BEV segmentation using` sparsebev `as a decoder?

**Comment by zbaishancha** [comment]
@raozhongyu @afterthat97

> Theoretically, it is possible. You can do it like PETRv2.

Hello dear author, have you tried to perform the related experiments? Can you share the result of the BEV segmentation? 
Best wishes to you！

**Comment by afterthat97** [comment]
We tried occupancy but not BEV segmention, https://arxiv.org/abs/2312.17118

**Comment by zbaishancha** [comment]
> We tried occupancy but not BEV segmentation, https://arxiv.org/abs/2312.17118

Thank you very much for your reply, I will try to finish this work in order to see the performance of sparsebev on BEV segmentation, I will keep you updated if there is any progress! :)
