### ISSUE TITLE
It seems that use the split val dataset for training besides the original split trainset under the nuscenes leaderboard submission config setting ? 

### ISSUE THREAD

**Issue by Slonna** [MCG-NJU/SparseBEV#50]
Such as  vov99_dd3d_1600x640_trainval_future .py ,I want to know that how about the results without the validation set for training . Is there any performance great drop? https://github.com/MCG-NJU/SparseBEV/blob/527428d4530741c7adc765d7b584a5cd1963b5d1/configs/vov99_dd3d_1600x640_trainval_future.py#L94-L98

**Comment by afterthat97** [comment]
I didn't try it. All previous methods on the leaderboard use train+val for training and I just followed their setting.

**Comment by Slonna** [comment]
Thanks for your swift reply!
