### ISSUE TITLE
Online Inference

### ISSUE THREAD

**Issue by YoushaaMurhij** [MCG-NJU/SparseBEV#51]
Thanks for sharing this great work!
I noticed that `simple_test_online` heavily depends on `filename` key in the input data dict. And uses it to check whether the image is already in the memory or not if I correclty understood this part of code. I wonder how to implement this for online streaming (i. e. video stream from mulitple cameras) without saving the frames into files. Is it costy to get rid of filenames in this function? 

Thanks

**Comment by afterthat97** [comment]
Hi, maybe you can use UUID to generate pseudo filenames.

https://stackoverflow.com/questions/534839/how-to-create-a-guid-uuid-in-python
