### ISSUE TITLE
Hi, I want to know that what isthe gen_sweep_info.py used for? Does SparseBEV use nuscenes sweeps data to train and inference?

### ISSUE THREAD

**Issue by Slonna** [MCG-NJU/SparseBEV#53]

**Comment by Slonna** [comment]
Dear author, wonderful work
What is the gen_sweep_info.py used for? 
Does SparseBEV use nuscenes sweeps data to train and inference?

**Comment by afterthat97** [comment]
Yes, but the sweep data is used only during training.

**Comment by Slonna** [comment]
However, I'm a little confused.
In gen_sweep_info.py，it also processes the test.pkl
https://github.com/MCG-NJU/SparseBEV/blob/527428d4530741c7adc765d7b584a5cd1963b5d1/gen_sweep_info.py#L97-L100
and also the config.py load sweeps?
https://github.com/MCG-NJU/SparseBEV/blob/527428d4530741c7adc765d7b584a5cd1963b5d1/configs/r50_nuimg_704x256.py#L139

**Comment by afterthat97** [comment]
https://github.com/MCG-NJU/SparseBEV/blob/527428d4530741c7adc765d7b584a5cd1963b5d1/loaders/pipelines/loading.py#L46

Actually we didn't use sweeps as the interval is 6

**Comment by Slonna** [comment]
Thanks for your swift reply!!!
