### ISSUE TITLE
去噪任务的影响

### ISSUE THREAD

**Issue by huichen98** [MCG-NJU/SparseBEV#55]
# noise on the box
            if self.dn_bbox_noise_scale > 0:
                wlh = known_bbox_expand[..., 3:6].clone()
                rand_prob = torch.rand_like(known_bbox_expand) * 2 - 1.0
                known_bbox_expand[..., 0:3] += torch.mul(rand_prob[..., 0:3], wlh / 2) * self.dn_bbox_noise_scale
                # known_bbox_expand[..., 3:6] += torch.mul(rand_prob[..., 3:6], wlh) * self.dn_bbox_noise_scale
                # known_bbox_expand[..., 6:7] += torch.mul(rand_prob[..., 6:7], 3.14159) * self.dn_bbox_noise_scale

作者你好，我试了一下打开后面两行代码，在自己数据集上似乎没有带来指标上的优化，想知道去噪任务对sparsebev来说作用有多大？
感谢

**Comment by afterthat97** [comment]
就中心点的dn比较有用，scale和orientation的都不涨点

**Comment by huichen98** [comment]
感谢答复，我们还发现在角度预测上 sparsebev 要优于bevformer，bevformer采样点虽然很密集，但由于是固定点，似乎收益不大

**Comment by afterthat97** [comment]
是的，灵活一点比较好

**Comment by Liiiiiiiu** [comment]
query denoising 要应用到bevformer中的话，效果会怎样，准备试一下，所以请教一下您是否建议这样做呢~

**Comment by afterthat97** [comment]
@Liiiiiiiu 这有啥好建议的，你想试试就试试呗，再说这应该去问bevformer作者

**Comment by Liiiiiiiu** [comment]
行，感谢~

**Comment by gaowei724** [comment]
> 行，感谢~

@Liiiiiiiu 你好，请问你有在bevformer上做加denoise的实验吗？我进行了一些实验，要不要交流一下。
