### ISSUE TITLE
Using flip augmentation in the training, how to align the preds bbox(on the flip imgs) to the unflip gt bbox of original ann_file？

### ISSUE THREAD

**Issue by Slonna** [MCG-NJU/SparseBEV#56]
Is it convenient for you to show some related code? ( I  have tried but not found it， Many thanks!)

**Comment by Slonna** [comment]
It seems that after flip the original image, just  change the lidar2img correspondingly (which is used only to change sampling points for prediction)?

**Comment by afterthat97** [comment]
Yes, modifying the lidar2img is enough.

https://github.com/MCG-NJU/SparseBEV/blob/527428d4530741c7adc765d7b584a5cd1963b5d1/loaders/pipelines/transforms.py#L219

**Comment by Slonna** [comment]
why is it enough? What I mean is that  flip the image will change the original gt bbox attribute (like the location,rotation)?
And I think the lidar2img  modification here just affects the sampling feature for prediction (which will regress to the unflipped GT box, which I think a little confused).

**Comment by Slonna** [comment]
> but the sampling points are correctly mapped, right? By aggregating the features of these points, we should be able to determine the rotation.

thanks for your reply! However, still a little confused. the "rotation" here is the original unfilped gt bbox's rotation or something else?

**Comment by afterthat97** [comment]
the original unfilped gt bbox's rotation

**Comment by Slonna** [comment]
I got it! Thanks for your swift reply!
