### ISSUE TITLE
unexpected key in source state_dict，missing keys in source state_dict

### ISSUE THREAD

**Issue by zbaishancha** [MCG-NJU/SparseBEV#57]
![image](https://github.com/MCG-NJU/SparseBEV/assets/106945649/51b12b8a-9ab1-400c-bd84-89f74204847e)
Hello dear author, when I was training `configs/r50_nuimg_704x256.py`, I found that the loaded pre-training model showed this prompt, is this normal and will it affect the final performance? 
(I guess it is because the downloaded pre-training weights are `cascade_mask_rcnn_r50_fpn_coco-20e_20e_nuim_20201009_124951-40963960.pth`, which is the weight of the img backbone, not the weight of the` sparsebev`, so there will be a case that some modules cannot be loaded)

**Comment by zbaishancha** [comment]
@afterthat97 best wish to you！

**Comment by afterthat97** [comment]
It is normal and your guess is right!

**Comment by zbaishancha** [comment]
> It is normal and your guess is right!

thanks, i will close this issue.
