### ISSUE TITLE
请问作者有没有做过不同query数量以及不同数量尺度特征图的消融实验？还有就是什么时候开源SparseOcc❥(^_-)

### ISSUE THREAD

**Issue by cheng-peng-git** [MCG-NJU/SparseBEV#58]

**Comment by afterthat97** [comment]
SparseBEV里面，query数量的ablation没做过，但试了400，900，1600，感觉是越多越好；

关于“不同数量尺度特征图”，c23456应该是最好的，尤其是在高分辨率输入时；

SparseOcc应该会在近期开源, 你可以先关注一下我们即将办的比赛

https://opendrivelab.com/challenge2024/#occupancy_and_flow

**Comment by cheng-peng-git** [comment]
感谢，非常期待接下来的工作
