### ISSUE TITLE
关于i_view[..., None].float() / 5 里 5 的含义

### ISSUE THREAD

**Issue by Ran-7759** [MCG-NJU/SparseBEV#6]
https://github.com/MCG-NJU/SparseBEV/blob/670087ce0cf382cca3a1884594d1c45db4daf56e/models/sparsebev_sampling.py#L87

请问下这行代码中，5 的含义表示的是 num_img_view - 1吗

**Comment by afterthat97** [comment]
对的，我们待会把这块加一下注释说明一下

**Comment by afterthat97** [comment]
注释已加，如果还有问题可以问我
