### ISSUE TITLE
SparseOcc当中sparse decoder部分的最后一层query数量是65536吗？以及第一部分的体素化分辨率是1.6m*1.6m*1.6m吗？

### ISSUE THREAD

**Issue by cheng-peng-git** [MCG-NJU/SparseBEV#61]

**Comment by afterthat97** [comment]
我们过一两周就会挂一版新的出来了，同时还会开源代码

**Comment by Joeless** [comment]
> 我们过一两周就会挂一版新的出来了，同时还会开源代码

你好预计什么时候会开源呢

**Comment by afterthat97** [comment]
大哥们别催了，让我先放个几天假吧好不好..
我比较佛，卷不动

**Comment by Qidian213** [comment]
@afterthat97 大佬，生产队的驴也不敢这样歇着

**Comment by afterthat97** [comment]
大哥们我就歇了一天，这几天在忙着组织比赛相关呢，稍安勿躁

https://github.com/OpenDriveLab/OccNet

**Comment by drilistbox** [comment]
大佬  有空的时候记得开源sparseocc哈  积极等待中

**Comment by afterthat97** [comment]
谢谢大家的期待，我已经在整理代码了，这两天让老板过一遍就可以开园了
