### ISSUE TITLE
About max points in msmv_sampling.cpp

### ISSUE THREAD

**Issue by Camellia-hz** [MCG-NJU/SparseBEV#63]
Hello Dear Author, I tried to increase the number of sampling points, but there is a bug: 
![image](https://github.com/MCG-NJU/SparseBEV/assets/106945649/ad49ec6d-71d3-4411-ba64-fc486e8e963d)

I found the following definition in `models/csrc/msmv_sampling/msmv_sampling.cpp`: `#define MAX_POINT 32` Is it possible to increase his value? Will it have some effect?

**Comment by zbaishancha** [comment]
@afterthat97

**Comment by zbaishancha** [comment]
I will try to use the pytorch version of the feature sampling function.

**Comment by afterthat97** [comment]
there is no problem if you increase MAX_POINT.
