### ISSUE TITLE
Performance of sparse voxel decoder

### ISSUE THREAD

**Issue by Yzichen** [MCG-NJU/SparseBEV#65]
Thank you for your work.
If purely doing semantic occupancy prediction, then it is acceptable to leave out the queries and mask transformer and let Sparse Voxel Decoder predict occupancy results directly. I would like to know how it performs this way?

**Comment by afterthat97** [comment]
会掉2-3个点，所以感觉还是需要maskformer来增强一下

**Comment by Yzichen** [comment]
那sparse voxel decoder的性能也很强了，要比bevdet-occ这种性能高不少，您觉得这是为什么呢？ 似乎在检测中，3D-to-2D 和 2D-to-3D的差距没这么大。

**Comment by afterthat97** [comment]
我给你学校邮箱发了个邮件，咱加微信聊吧

**Comment by ryontang** [comment]
> 那sparse voxel decoder的性能也很强了，要比bevdet-occ这种性能高不少，您觉得这是为什么呢？ 似乎在检测中，3D-to-2D 和 2D-to-3D的差距没这么大。

您好 我对这个问题也很感兴趣，请问有什么讨论群吗？
