### ISSUE TITLE
sampling_4d

### ISSUE THREAD

**Issue by jhjun724** [MCG-NJU/SparseBEV#66]
Hello, thank you for your awesome work and its sharing.

I have one question in your code, `SparseBEV/models/sparsebev_sampling.py`.

In `sampling_4d`, `sampling_pts`  is reshaped into `BTG x Q x P x3` in [#L114](https://github.com/MCG-NJU/SparseBEV/blob/main/models/sparsebev_sampling.py#L114), but `scale_weights` is reshaped into `BGT x Q x P x L` in [#L119](https://github.com/MCG-NJU/SparseBEV/blob/main/models/sparsebev_sampling.py#L119).
Due to these different transposes of two tensors, the final shape is same but the ordering is quite different.
Is the different ordering between `B*T*G` and `B*G*T` intended for `msmv_sampling`?

Thank you.

**Comment by afterthat97** [comment]
It's a bug, but it doesn't affect performance. See #24 for more details.

**Comment by jhjun724** [comment]
Oh, I didn't check the Closed issues.
Thank you for your quick reply.
