### ISSUE TITLE
decoder layer里的add & norm

### ISSUE THREAD

**Issue by Azeral0619** [MCG-NJU/SparseBEV#69]
为什么[代码](https://github.com/MCG-NJU/SparseBEV/blob/main/models/sparsebev_transformer.py#L169)里只有layer norm没有add

**Comment by afterthat97** [comment]
有吧，比如mixing末尾就有：

https://github.com/MCG-NJU/SparseBEV/blob/024778a5fb4eb98a1b72dd6e2e16b054fea87c94/models/sparsebev_transformer.py#L379

self attention也有，在multiHeadAttention的官方实现里面
