### ISSUE TITLE
如何生成nuscenes_info_train.pkl文件？

### ISSUE THREAD

**Issue by kingofstu** [MCG-NJU/SparseBEV#72]
你好，gen_sweep_info.py脚本生成nuscenes_infos_train_sweep.pkl文件得先有nuscenes_info_train.pkl文件，那我该怎么生成nuscenes_info_train.pkl文件？

**Comment by Zhh512** [comment]
> 你好，gen_sweep_info.py脚本生成nuscenes_infos_train_sweep.pkl文件得先有nuscenes_info_train.pkl文件，那我该怎么生成nuscenes_info_train.pkl文件？

你好，请问解决了吗，我也疑惑这个；我试着用的mmdetection3d的tools里转的，但还是报错了，不知道作者是用啥生成的；

**Comment by YANG-CY-163** [comment]
nuscenes_info_train.pkl文件可以用[mmdetection3d](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0rc6)的tools生成，`python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes`，请问你遇到什么报错了呢

**Comment by kingofstu** [comment]
> nuscenes_info_train.pkl文件可以用[mmdetection3d](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0rc6)的tools生成，`python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes`，请问你遇到什么报错了呢

已解决，感谢

**Comment by kingofstu** [comment]
> nuscenes_info_train.pkl文件可以用[mmdetection3d](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0rc6)的tools生成，`python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes`，请问你遇到什么报错了呢

已解决，感谢

**Comment by lht6806** [comment]
请问您怎么处理的呀，我也遇到了情况python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes，这个命令报错了

**Comment by kingofstu** [comment]
显示啥错呢，我运行这个没问题
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月30日 11:05 ***@***.***> ***@***.***>,
***@***.***>主题Re: [MCG-NJU/SparseBEV] 如何生成nuscenes_info_train.pkl文件？ (Issue #72)
请问您怎么处理的呀，我也遇到了情况python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes，这个命令报错了

**Comment by wolfcanli** [comment]
> nuscenes_info_train.pkl文件可以用[mmdetection3d](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0rc6)的tools生成，`python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes`，请问你遇到什么报错了呢
您好，请问要生成这些文件，是不是需要将nuscenes所有数据集都下载呢？如果只下载mini版本数据是不是不行？谢谢呀

**Comment by 13512525** [comment]
> 请问您怎么处理的呀，我也遇到了情况python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes，这个命令报错了

你好，请问问题解决了吗？
