### ISSUE TITLE
关于calculate absolute velocity according to time difference

### ISSUE THREAD

**Issue by kingofstu** [MCG-NJU/SparseBEV#75]
time_diff = img_metas[0]['time_diff']  # [B, F]
if time_diff.shape[1] > 1:
    time_diff = time_diff.clone()
    time_diff[time_diff < 1e-5] = 1.0
    bbox_pred[..., 8:] = bbox_pred[..., 8:] / time_diff[:, 1:2, None]
您好，可否告知一下/ time_diff[:, 1:2, None]是在干啥，为什么是取最邻近的前一个sweep呢？

**Comment by YANG-CY-163** [comment]
取最邻近的前一个sweep是为了得到和相邻sweep的时间差，/ time_diff[:, 1:2, None] 是把中心点位移除以时间差得到瞬时速度
