### ISSUE TITLE
pkl问题

### ISSUE THREAD

**Issue by lht6806** [MCG-NJU/SparseBEV#78]
作者好呀，我遇到个问题
工程中提供的生成pkl的脚本是不是少加了属性呀？
我用这个脚本生成pkl之后，报了
    lidar2cam_r = np.linalg.inv(cam_info['cam2lidar_rotation'])
KeyError: 'cam2lidar_rotation'

**Comment by afterthat97** [comment]
我只删了这几个key，其他没动

https://github.com/MCG-NJU/SparseBEV/blob/024778a5fb4eb98a1b72dd6e2e16b054fea87c94/gen_sweep_info.py#L59-L64

**Comment by lht6806** [comment]
问题一开始是这样的，gen_sweep_info.py中有个需要load文件的地方：sample_infos = pickle.load(open(os.path.join(args.data_root, 'nuscenes_infos_train_mini.pkl'，），但我没发现nuscenes_infos_train_mini.pkl这个文件呀，请问在哪里获取呀？

**Comment by lht6806** [comment]
作者能不能给解答一下疑惑呀

**Comment by afterthat97** [comment]
你先看看mmdet3d的nuscenes预处理部分吧

**Comment by lht6806** [comment]
好的，我先看一下，多谢啦
