### ISSUE TITLE
按照论文采集8帧，128个点，那mixing中的out_features有8w参数，显存不爆吗

### ISSUE THREAD

**Issue by rubbish001** [MCG-NJU/SparseBEV#8]

**Comment by afterthat97** [comment]
Mixing 的输入是 `[B, Q, G, TxP, C]` 的形状（这几个符号的含义可以见 https://github.com/MCG-NJU/SparseBEV/blob/main/models/sparsebev_sampling.py#L35）；按r50_nuimg_704那个配置的话，B=1, Q=900, G=4, T=8, P=4, C=64, 这个tensor只有大约7M的元素，实际上占用的显存很少

**Comment by rubbish001** [comment]
我的意思是您刷最好的结果的时候应该用P=16把，那么
  (mixing): AdaptiveMixing(
            (parameter_generator): Linear(in_features=256, out_features=81920, bias=True)
            (out_proj): Linear(in_features=32768, out_features=256, bias=True)
            (act): ReLU(inplace=True)
          )
中的out_features=81920，感觉参数有点多了，我的玩法也是刷点数的，我感觉采集样本的点个数应该是p5层中20X50个数的四分之一，效果比较好，我是玩单帧的

**Comment by rubbish001** [comment]
哦哦哦，谢谢，明白了

**Comment by rubbish001** [comment]
![image](https://github.com/MCG-NJU/SparseBEV/assets/4549184/4abf8c05-3212-47bd-923d-090efe989ef8)
G应该表示对通道数进行分组，这样加速采用。从这个图中可以得出point应该是16，然后是8帧，那个(mixing): AdaptiveMixing(
(parameter_generator): Linear(in_features=256, out_features=81920, bias=True)
(out_proj): Linear(in_features=32768, out_features=256, bias=True)
(act): ReLU(inplace=True)
)
现在又几个问题，第一个问题，这个参数量是不是有点大，我觉得采用32个点的时候应该是效果最好的，可能是参数量太大，没有训练好导致的。第二，怎么设置的p=16，p=16的时候直接报
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
第三在Deformable DETR中采样点是4,，但是C5层的大小是7*7，当图片是1600*640的时候，C5层的大小为50*20，采样点应该是250个左右比较好，当然我这只是分析一下。
现在主要是解决第二个问题。第一，第三个问题还可以互相交流一下

**Comment by afterthat97** [comment]
关于第二点，我刚刚不是说了，p=16是总共全部4组的，每组4个点，也就是config里面的num points=4就已经是论文中p=16的结果了

**Comment by afterthat97** [comment]
你如果设置num point=16，就相当每帧有64个采样点了，又有8帧，肯定吃不消

**Comment by rubbish001** [comment]
请问一下，这个mixing结构是哪里借鉴来的，我感觉是综合了多头注意中的通道数Cat操作，又借鉴了Sparse R-CNN的dynamicConv的结果，不知道那篇论文第一个发现这种结果的

**Comment by afterthat97** [comment]
AdaMixer

**Comment by afterthat97** [comment]
关于第一点和第三点的话，确实可能是优化有难度，也可能是实验有noise（加到32之后掉0.1 NDS，也在noise范围内）

**Comment by afterthat97** [comment]
代码里写的0.5啊，就是用这个训的

**Comment by rubbish001** [comment]
能不能把vov99_dd3d_1600x640_trainval_future这个训练日志发我邮箱一份，我的训练有点问题，邮箱liwenx@whu.edu.cn

**Comment by afterthat97** [comment]
你这是没收敛啊，你确定是用这个配置，啥也没动吗

**Comment by rubbish001** [comment]
我只是参考一下你的训练过程，我也知道没有收敛，我感觉第一个epoch下来，应该是在1.8左右，我看看你的跟我猜的是不是一样的

**Comment by rubbish001** [comment]
有没有测试单帧在1600*640 v299，上面的效果，超过mAp42.9或者44.1没有

**Comment by afterthat97** [comment]
我们在第一个epoch结束之后bbox loss到了1左右

**Comment by afterthat97** [comment]
单帧在1600*640 v299没试过，你可以试一下

**Comment by rubbish001** [comment]
咱实验室就4张3090，跑不了，所以写代码格外小心，CMT-C是42.9，PETR是44.1，如果你们这种方式有效，我感觉我这种思路应该没有问题

**Comment by rubbish001** [comment]
C5层的大小和采样点的个数的关系有没有相关的论文，我想参考一下哈

**Comment by afterthat97** [comment]
这个我不知道，我们就是随便调调出来的

**Comment by rubbish001** [comment]
牛，改写cuda版本采样方式，套用adamixing方式，看来要跟论文了

**Comment by afterthat97** [comment]
参考训练日志你自己跑一个r50的就行了吧，很快的

**Comment by afterthat97** [comment]
也可以给你发一份，不过得过一两天

**Comment by rubbish001** [comment]
我计算资源非常有限，只能跑钱几轮判断程序出现的问题，麻烦随便发一个给我参考一下哈，我只是在你的基础上把图像和点云融合一下，我感觉有戏

**Comment by rubbish001** [comment]
这个网络只有主干网络部分是半精度，其他地方都是f32吗，不收敛萨出现了nan

**Comment by rubbish001** [comment]
修复了一下我的程序的bug，刚开始后迭代700次后为1.65左右吗

**Comment by rubbish001** [comment]
还有，这个query数等于1600的时候是多少，有训练过吗？我看PETR是1500

**Comment by afterthat97** [comment]
已发。

**Comment by rubbish001** [comment]
有没有v299的，类似这个：
09/20 00:31:10 - mmengine - INFO - Epoch(train)  [1][ 2300/15448]  lr: 2.5000e-05  eta: 4 days, 19:56:50  time: 1.3459  data_time: 0.0460  memory: 15845  grad_norm: 44.8744  loss: 17.5884  loss_cls_dn: 0.0778  loss_bbox_dn: 0.7500  d0.loss_cls_dn: 0.0709  d0.loss_bbox_dn: 0.6741  d1.loss_cls_dn: 0.0669  d1.loss_bbox_dn: 0.6815  d2.loss_cls_dn: 0.0682  d2.loss_bbox_dn: 0.6963  d3.loss_cls_dn: 0.0709  d3.loss_bbox_dn: 0.7123  d4.loss_cls_dn: 0.0741  d4.loss_bbox_dn: 0.7302  loss_cls: 0.5480  loss_bbox: 1.5438  d0.loss_cls: 0.5372  d0.loss_bbox: 1.6964  d1.loss_cls: 0.5339  d1.loss_bbox: 1.6868  d2.loss_cls: 0.5491  d2.loss_bbox: 1.6149  d3.loss_cls: 0.5412  d3.loss_bbox: 1.5675  d4.loss_cls: 0.5438  d4.loss_bbox: 1.5525
09/20 00:32:18 - mmengine - INFO - Epoch(train)  [1][ 2350/15448]  lr: 2.5000e-05  eta: 4 days, 19:55:50  time: 1.3625  data_time: 0.0454  memory: 15864  grad_norm: 43.2751  loss: 17.3895  loss_cls_dn: 0.0709  loss_bbox_dn: 0.7251  d0.loss_cls_dn: 0.0672  d0.loss_bbox_dn: 0.6545  d1.loss_cls_dn: 0.0630  d1.loss_bbox_dn: 0.6595  d2.loss_cls_dn: 0.0639  d2.loss_bbox_dn: 0.6764  d3.loss_cls_dn: 0.0657  d3.loss_bbox_dn: 0.6912  d4.loss_cls_dn: 0.0682  d4.loss_bbox_dn: 0.7075  loss_cls: 0.5297  loss_bbox: 1.5541  d0.loss_cls: 0.5271  d0.loss_bbox: 1.6920  d1.loss_cls: 0.5279  d1.loss_bbox: 1.6928  d2.loss_cls: 0.5334  d2.loss_bbox: 1.6187  d3.loss_cls: 0.5291  d3.loss_bbox: 1.5797  d4.loss_cls: 0.5272  d4.loss_bbox: 1.5645
^[a^A09/20 00:33:26 - mmengine - INFO - Epoch(train)  [1][ 2400/15448]  lr: 2.5000e-05  eta: 4 days, 19:54:05  time: 1.3553  data_time: 0.0455  memory: 16250  grad_norm: 46.8801  loss: 17.3096  loss_cls_dn: 0.0629  loss_bbox_dn: 0.7349  d0.loss_cls_dn: 0.0632  d0.loss_bbox_dn: 0.6481  d1.loss_cls_dn: 0.0589  d1.loss_bbox_dn: 0.6521  d2.loss_cls_dn: 0.0591  d2.loss_bbox_dn: 0.6728  d3.loss_cls_dn: 0.0598  d3.loss_bbox_dn: 0.6925  d4.loss_cls_dn: 0.0611  d4.loss_bbox_dn: 0.7133  loss_cls: 0.5379  loss_bbox: 1.5316  d0.loss_cls: 0.5325  d0.loss_bbox: 1.6986  d1.loss_cls: 0.5324  d1.loss_bbox: 1.6799  d2.loss_cls: 0.5439  d2.loss_bbox: 1.6004  d3.loss_cls: 0.5373  d3.loss_bbox: 1.5596  d4.loss_cls: 0.5337  d4.loss_bbox: 1.543
