### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Cuiyanhu** [MCG-NJU/SparseBEV#83]
指令conda install pytorch==2.0.0 torchvision==0.15.0 pytorch-cuda=11.8 -c pytorch -c nvidia安装torch环境
lib文件夹中确实没有libtorch_cuda_cu.so文件，只有libtorch_cuda.so文件
![1726043497014](https://github.com/user-attachments/assets/fc6898bc-68ca-4ba6-8f4c-413552d1cecf)
![image](https://github.com/user-attachments/assets/aa688e68-55f4-4ca6-a71e-6c07a425bbbc)
求一份详细的环境文档，万分感谢

**Comment by GreenLazy-222** [comment]
你好，我也遇到了这个问题，请问怎么解决的呢

**Comment by Cuiyanhu** [comment]
> 你好，我也遇到了这个问题，请问怎么解决的呢

我是mmcv文件里面报出这个错误的，mmcv-full 1.6.0和torch2.0.0不匹配（不清楚官方这个为什么可以），我换成了mmcv-full 1.7.0就行了（报错版本不匹配的话就修改下源码），后面其他环境都一样的

**Comment by GreenLazy-222** [comment]
谢谢你的答复！
