### ISSUE TITLE
关于代码在mmdet3d v0.17.1版本下的运行问题

### ISSUE THREAD

**Issue by explorer-shy** [MCG-NJU/SparseBEV#86]
我想在mmdet3d v0.17.1下运行该代码，我尝试修改了utils下的version为0.17.1但是最终效果仍然不好，能否告诉我应该如何修改？或者能否发一份v0.17.1下正常训练的代码？我的邮箱是1749697503@qq.com，谢谢！

**Comment by explorer-shy** [comment]
我已经搞定了这个问题，所以我将会关闭这个issue

**Comment by kingofstu** [comment]
> 我已经搞定了这个问题，所以我将会关闭这个issue

您好，可否告知一下您是如何解决这个问题的，做了哪些修改？
