### ISSUE TITLE
Pretrain weights download

### ISSUE THREAD

**Issue by 1uciusy** [MCG-NJU/SparseBEV#9]
Hi, I see the the part of **Training** says:

Download pretrained weights and put it in directory `pretrain/`:

```
pretrain
├── cascade_mask_rcnn_r101_fpn_1x_nuim_20201024_134804-45215b1e.pth
├── cascade_mask_rcnn_r50_fpn_coco-20e_20e_nuim_20201009_124951-40963960.pth
```

Where should I download these weights? Are there correspondence between these two weights and the four weights in **Model Zoo**

**Comment by afterthat97** [comment]
You can download them from the "pretrain" column (not the "weights" column) of the model zoo table.

**Comment by 1uciusy** [comment]
ohhhh many thx
